services:
  app:
    build: .
    image: dguilliams3/nlp_demo:latest
    environment:
      CONFIG_FILE: config.yaml
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials/${GOOGLE_CREDENTIALS_FILE}
    volumes:
      - ./credentials:/app/credentials
