name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 2025-03-AWS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Inject credentials filename into Dockerrun.aws.json
        run: |
          sed -i "s/\${GOOGLE_CREDENTIALS_FILE}/${{ secrets.GOOGLE_CREDENTIALS_FILE }}/g" Dockerrun.aws.json

      - name: Install EB CLI and Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          pip install awsebcli

          # Deploy to preconfigured environment
          eb deploy nlp-demo-env
